use_frameworks!

platform :ios, '9.0'

target 'GCMultiLevelTableView_Example' do
  pod 'GCMultiLevelTableView', :path => '../'

  target 'GCMultiLevelTableView_Tests' do
    inherit! :search_paths

    
  end
end
